# REGISTRY HOST = fully qualified registry name

name: basket-api

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        default: 'Build and Deploy basket-api'
        required: false
  
  push:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml

env:
  SERVICE: basket-api
  IMAGE: basket.api
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RG }}
  ACR_USERNAME: ${{ secrets.USERNAME }}
  ACR_PASSWORD: ${{ secrets.PASSWORD }}
  DEPLOY_INFRA: ${{ github.event.inputs.deployInfra }}
  APPINSIGHTS_KEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATION }}

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
      
    - name: Compose build ${{ env.SERVICE }}
      run: sudo -E docker-compose build ${{ env.SERVICE }}
      working-directory: ./src
      shell: bash
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}

  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Enable experimental features for the Docker daemon and CLI
      run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Set branch name as env variable
      run: |
        currentbranch=$(echo ${GITHUB_REF##*/})
        echo "running on $currentbranch"
        echo "BRANCH=$currentbranch" >> $GITHUB_ENV
      shell: bash

    - name: Compose build ${{ env.SERVICE }}
      run: sudo -E docker-compose build ${{ env.SERVICE }}
      working-directory: ./src
      shell: bash
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}

    - name: Compose push ${{ env.SERVICE }}
      run: sudo -E docker-compose push ${{ env.SERVICE }}
      working-directory: ./src
      shell: bash
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}

    - name: Create multiarch manifest
      run: |
        docker --config ~/.docker manifest create ${{ secrets.REGISTRY_ENDPOINT  }}/${{ env.IMAGE  }}:${{ env.BRANCH  }} ${{ secrets.REGISTRY_ENDPOINT  }}/${{ env.IMAGE  }}:linux-${{ env.BRANCH  }}
        docker --config ~/.docker manifest push ${{ secrets.REGISTRY_ENDPOINT  }}/${{ env.IMAGE  }}:${{ env.BRANCH  }}
      shell: bash

  DeployImageTok8s:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Deployment PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |          
          # Get AKS credentials for kubectl
          az aks get-credentials --resource-group $Env:CLUSTER_RESOURCE_GROUP --name $Env:CLUSTER_NAME 
          
          echo "services to update:"
          echo $Env:SERVICE

          # Set container registry url 
          $containerRegistry = $Env:REGISTRY_NAME + '.azurecr.io'
          cd $Env:GITHUB_WORKSPACE/deploy/k8s/helm
          . $Env:GITHUB_WORKSPACE/deploy/k8s/helm/deploy-singular-service.ps1 -externalDns aks -aksName $Env:CLUSTER_NAME -aksRg $Env:CLUSTER_RESOURCE_GROUP -imageTag linux-dev -registry $containerRegistry -dockerUser $Env:ACR_USERNAME -dockerPassword $Env:ACR_PASSWORD -deployInfrastructure $false -useMesh $false -chartsToDeploy $Env:SERVICE
          
          
          # Show deployment status
          kubectl get deployment
          
          # Display webMVC and webSPA URLs 
          kubectl get ingresses -o jsonpath='{.spec.rules[*].host}{.spec.rules[*].http.paths[*].path}' eshop-webspa 
          echo "`n"
          kubectl get ingresses -o jsonpath='{.spec.rules[*].host}{.spec.rules[*].http.paths[*].path}' eshop-webmvc 
          
          # Add the Application Insights instrumentation key deployment as an environment variable
          $deployment = kubectl get deployments -l app=$Env:SERVICE -o jsonpath="{.items[0].metadata.name}"
          echo "Adding Application Insights Instrumentation Key to $deployment `n"
          kubectl set env deployments $deployment ApplicationInsights__InstrumentationKey=$Env:APPINSIGHTS_KEY
        azPSVersion: '3.1.0'